### ISSUE TITLE
kwm-overlay crashes/won't build with newest Xcode update

### ISSUE THREAD

**Issue by weruder** [koekeishiya/kwm#251]
After updating to 10.11.4 and the new Xcode update it was working fine at first but after a restart the overlay kept going through a loop of constantly restarting:
```
Crashed Thread:        0

Exception Type:        EXC_BREAKPOINT (SIGTRAP)
Exception Codes:       0x0000000000000002, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Symbol not found: __TMPdSa
  Referenced from: /usr/local/bin/kwm-overlay
  Expected in: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/macosx/libswiftCore.dylib
 in /usr/local/bin/kwm-overlay

```

And while trying to do a new build there are errors as well:

```
kwm-overlay/kwm-overlay.swift:196:34: error: 'NSWindowTitleVisibility' is only available on OS X 10.10 or newer
        window.titleVisibility = NSWindowTitleVisibility.Hidden
kwm-overlay/kwm-overlay.swift:196:16: error: 'titleVisibility' is only available on OS X 10.10 or newer
        window.titleVisibility = NSWindowTitleVisibility.Hidden
kwm-overlay/kwm-overlay.swift:197:16: error: 'titlebarAppearsTransparent' is only available on OS X 10.10 or newer
        window.titlebarAppearsTransparent = true
kwm-overlay/kwm-overlay.swift:199:29: error: 'NSFullSizeContentViewWindowMask' is only available on OS X 10.10 or newer
        window.styleMask |= NSFullSizeContentViewWindowMask
```

**Comment by koekeishiya** [comment]
I can't even download the new Xcode because app store is just working so amazingly well..
Did you update to the latest command line tools? If not, do `xcode-select --install` and try to recompile afterwards.

**Comment by dominiklohmann** [comment]
I downloaded it via `softwareupdate --install --all`, that worked just fine. Can reproduce the issue after installing Xcode, it was fine with the previous version of Xcode on 10.11.4 before that.

**Comment by weruder** [comment]
If I'm not mistaken the command line tools were updated along with Xcode. Using `xcode-select --install` gives me this: 
`xcode-select: error: command line tools are already installed, use "Software Update" to install updates`
So I believe everything is up to date, there are no pending updates using `softwareupdate` anyway.
